ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.aegis_v3_sentinel]
path = "out/AegisV3Sentinel.sol/AegisV3Sentinel.json"
response_contract = "0xEFB450504f7391dE6Fc64aA9c9234B50737C353c"
response_function = "handleRisk(uint8,uint256,uint256,uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0x689Ad0f9cBa2dA64039cF894E9fB3Aa6266861D8"]
address = "0x047aEdd2215C6E22E1a8128A9A98735FfF666aff"
